name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        app: [client, server]
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Pull changes
        run: git pull origin main
        working-directory: /var/www/pondus_app

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            /var/www/pondus_app/${{ matrix.app }}/node_modules
            /root/.npm
          key: ${{ runner.os }}-node-${{ matrix.app }}-${{ matrix.node-version }}-${{ hashFiles('subdir/${{ matrix.app }}/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.app }}-${{ matrix.node-version }}-

      - name: Install dependencies
        run: npm ci
        working-directory: /var/www/pondus_app/${{ matrix.app }}

      - name: Check for client changes
        if: ${{ matrix.app == 'client' }}
        id: client_changes
        run: |
          git diff --name-only HEAD^ HEAD -- subdir/client | grep . || echo "no_changes"

      - name: Build client
        if: ${{ matrix.app == 'client' && steps.client_changes.outputs.no_changes != 'no_changes' }}
        run: npm run build
        working-directory: /var/www/pondus_app/client

      - name: Check for server changes
        if: ${{ matrix.app == 'server' }}
        id: server_changes
        run: |
          git diff --name-only HEAD^ HEAD -- subdir/server | grep . || echo "no_changes"

      - name: Restart server
        if: ${{ matrix.app == 'server' && steps.server_changes.outputs.no_changes != 'no_changes' }}
        run: pm2 restart "Pondus Server"