name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull changes
        run: git pull origin main
        working-directory: /var/www/pondus_app

      - name: Install client dependencies
        run: npm ci
        working-directory: /var/www/pondus_app/client

      - name: Build client
        run: npm run build
        working-directory: /var/www/pondus_app/client

      - name: Install server dependencies
        run: npm ci
        working-directory: /var/www/pondus_app/server

      - name: Restart server
        run: pm2 restart "Pondus Server"
